version: '3'

services:
  postgres:
      container_name: postgres
      image: postgres:14-alpine3.15
      networks:
        - backend
      # volumes:
      #   - postgres-data
      env_file:
        - ./db/postgres.env
      ports:
        - 5432:5432
      logging:
        driver: none
  auth-api:
    container_name: auth-api
    build:
      context: auth-api
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 3000:3000
    env_file: ./auth-api/.env
  nginx:
    container_name: nginx
    image: nginx:1.22.1-alpine
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:v4.15.2
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      API_URL: docs/swagger.yml
    volumes:
      - type: bind
        source: ./swagger-ui/swagger.yml
        target: /usr/share/nginx/html/docs/swagger.yml
  # nestjs:
  #   container_name: nestjs
  #   build:
  #     context: app
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - "postgres"
  #   logging:
  #     driver: none

# volumes:
#   postgres-data:

networks:
  backend:
    name: backend_net
    driver: bridge