version: '3'

services:

  postgres:
      container_name: postgres
      image: postgres:latest
      networks:
        - backend
      env_file:
        - .env
      ports:
        - 5432:5432
      volumes:
       - postgres-data:/var/lib/postgresql/data
      
  auth-api:
    container_name: auth-api
    build:
      context: auth-api
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 3000:3000
    env_file: .env

  nginx:
    container_name: nginx
    image: nginx:1.22.1-alpine
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:v4.15.2
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      API_URL: docs/swagger.yml
    volumes:
      - type: bind
        source: ./swagger-ui/swagger.yml
        target: /usr/share/nginx/html/docs/swagger.yml

  chat:
    container_name: chat
    build:
      context: chat
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 3001:3000
    depends_on:
      - "postgres"
  
volumes:
  postgres-data:

networks:
  backend:
    name: backend_net
    driver: bridge